@server = https://mariamc28-fantastic-winner-vx7767469rrhx9j7-8080.preview.app.github.dev

###

GET {{server}}
###
GET {{server}}/categorias

###
GET {{server}}/categorias?size=2

###
GET {{server}}/categorias?size=2&page=1

###
GET {{server}}/categorias?sort=creditos,desc

###
GET {{server}}/categorias?size=2&page=1&sort=creditos,desc

### 
POST {{server}}/categorias
Content-Type: application/json

{"nombre": "Instrumento de viento"}


###

DELETE {{server}}/categorias/203

###
GET {{server}}/categorias/search/findByNombre?nombre=Instrumento de viento
###
GET {{server}}/categorias
###
GET {{server}}/profile/categorias
###
GET {{server}}/instrumentos/categorias
###


#################


GET {{server}}/instrumentos
###
GET {{server}}/instrumentos/2/categorias
###
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Flauta"}

### 
PATCH {{server}}/categorias/2
Content-Type: application/json

{"id_instrumentos": 2}



###
GET {{server}}/cursos/52/carrera